steps:
- name: "us-central1-docker.pkg.dev/m2c-demo/container/witwdt:v2"
  script: |
    #!/usr/bin/env bash

    /tools/imagetool/bin/imagetool.sh cache deleteEntry --key wdt_latest

    /tools/imagetool/bin/imagetool.sh cache addInstaller \
      --type wdt \
      --version latest \
      --path /tools/weblogic-deploy.zip
        
    zip -r /workspace/archive.zip /workspace/deployment
    
    /tools/imagetool/bin/imagetool.sh update \
      --tag us-central1-docker.pkg.dev/m2c-demo/container/weblogic-demo-app:v1 \
      --fromImage us-central1-docker.pkg.dev/m2c-demo/container/weblogic:12.2.1.4  \
      --wdtModel /workspace/model.10.yaml \
      --wdtVariables /workspace/model.10.properties \
      --wdtArchive /workspace/archive.zip \
      --wdtModelOnly \
      --wdtDomainType WLS \
      --chown oracle:root

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: create-release
  entrypoint: gcloud
  args:
  - 'deploy' 
  - 'releases'
  - 'create' 
  - 'weblogic-on-gke-demo-release-$SHORT_SHA'
  - '--delivery-pipeline'
  - 'weblogic-on-gke-demo'
  - '--region'
  - 'us-central1'
  - '--from-k8s-manifest'
  - 'k8s/domain.yaml'

images:
  - us-central1-docker.pkg.dev/m2c-demo/container/weblogic-demo-app:v1