steps:
- name: "us-central1-docker.pkg.dev/m2c-demo/container/witwdt:v2"
  script: |
    #!/usr/bin/env bash

    /tools/imagetool/bin/imagetool.sh cache addInstaller \
      --type wdt \
      --version latest \
      --path /tools/weblogic-deploy.zip
    
    zip -r archive.zip applications config
    
    /tools/imagetool/bin/imagetool.sh update \
      --tag us-central1-docker.pkg.dev/m2c-demo/container/weblogic-demo-app:v1 \
      --fromImage us-central1-docker.pkg.dev/m2c-demo/container/weblogic:12.2.1.4  \
      --wdtModel model.10.yaml \
      --wdtVariables model.10.properties \
      --wdtArchive archive.zip \
      --wdtModelOnly \
      --wdtDomainType WLS \
      --chown oracle:root

# - name: "us-central1-docker.pkg.dev/m2c-demo/container/witwdt:v2"
#   id: skaffold-build
#   entrypoint: skaffold
#   args: ['build', '--file-output=/workspace/skaffold-output.json', '-v', 'trace', '--push']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: create-release
  entrypoint: gcloud
  args:
  - 'deploy' 
  - 'releases'
  - 'create' 
  - 'weblogic-on-gke-demo-release-$SHORT_SHA'
  - '--delivery-pipeline'
  - 'weblogic-on-gke-demo'
  - '--region'
  - 'us-central1'
  - '--from-k8s-manifest'
  - 'k8s/domain.yaml'
  # - '--skaffold-file'
  # - 'skaffold.yaml'
  # - '--build-artifacts'
  # - '/workspace/skaffold-output.json'

images:
  - us-central1-docker.pkg.dev/m2c-demo/container/weblogic-demo-app:v1