apiVersion: skaffold/v4beta8
kind: Config
build:
  # tagPolicy:
  #   envTemplate:
  #     template: "{{.SHORT_SHA}}"
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/weblogic-demo-app
    custom:
      buildCommand: ./build.sh
manifests: 
  rawYaml:
  - k8s/*.yml